name: "Multi Store Merge"

on:
  push:

jobs:
  merge:
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Shopify Multi Store Deployer
        uses: jamiemccleave/shopify-multi-store-deployer@v2.0
        with:
          from_branch: "master"
          to_branch: "stores/store-name/master-region"
          push_token: "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 "
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YOUR_PUSH_TOKEN: ${{ secrets.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 }}